apiVersion: v1
kind: Service
metadata:
  name: sample-app
  labels:
    app: sample-app
    chart: sample-app-0.1.0
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sample-app

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
    chart: sample-app-0.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: "microsoft/dotnet-samples:aspnetapp"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
